//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VVPEntities : DbContext
    {
        public VVPEntities()
            : base("name=VVPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Awards> Awards { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Scholarships> Scholarships { get; set; }
        public virtual DbSet<Students> Students { get; set; }
    }
}
